### ISSUE TITLE
Question about storage statemachine 

### ISSUE THREAD

**Issue by txm119161336** [tetrapods/raft#3]
Hi,

I  found  every time you commit the executing info to the disc and you do the snapshot as well , why you do it like this ,as what i am thinking ,doing logging is enough ,why we still snapshot , if what you mean is  making the recovery process faster ?

**Comment by artichikin** [comment]
It should only be doing a snapshot after every Log.NUM_ENTRIES_PER_SNAPSHOT entires are committed, not after every entry. Snapshotting state allows us to throw away all the older log entries (i.e. log compaction) since we can always start up from the snapshot instead of replaying all the older entries.

**Comment by txm119161336** [comment]
i understand what you said, but for compaction part ,you simply just remove the entries from the memo,there is no disk involved ?
how do deal with delete things ,like tombstone entry things.  
and for snapshot , how does the followers deal with the snapshot sent by leader   ,just compare the 
index  ,and the remove the old one?

**Comment by artichikin** [comment]
If you remove entries and don't have a snapshot, you have no way to restore a node to the correct state if you shut all nodes down. Snapshots aid in recovery. They also allow sending a new node a recent snapshot + remaining log, instead of the entire log. 

Some trivial state machines don't need snapshots, but anything non-trivial does.
